//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacturaElectronica.Ui.Win.Administrador.ServiceReferenceAfipWrapperService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceAfipWrapperService.IAfipWrapperService")]
    public interface IAfipWrapperService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAfipWrapperService/GetTiposMonedas", ReplyAction="http://tempuri.org/IAfipWrapperService/GetTiposMonedasResponse")]
        FacturaElectronica.Afip.Ws.Wsfe.MonedaResponse GetTiposMonedas(FacturaElectronica.Afip.Ws.Wsfe.FEAuthRequest feAuthRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAfipWrapperService/GetCotizacion", ReplyAction="http://tempuri.org/IAfipWrapperService/GetCotizacionResponse")]
        FacturaElectronica.Afip.Ws.Wsfe.FECotizacionResponse GetCotizacion(FacturaElectronica.Afip.Ws.Wsfe.FEAuthRequest feAuthRequest, string MonId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAfipWrapperService/GetTiposCbte", ReplyAction="http://tempuri.org/IAfipWrapperService/GetTiposCbteResponse")]
        FacturaElectronica.Afip.Ws.Wsfe.CbteTipoResponse GetTiposCbte(FacturaElectronica.Afip.Ws.Wsfe.FEAuthRequest feAuthRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAfipWrapperService/GetTiposTributos", ReplyAction="http://tempuri.org/IAfipWrapperService/GetTiposTributosResponse")]
        FacturaElectronica.Afip.Ws.Wsfe.FETributoResponse GetTiposTributos(FacturaElectronica.Afip.Ws.Wsfe.FEAuthRequest feAuthRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAfipWrapperService/GetTiposIva", ReplyAction="http://tempuri.org/IAfipWrapperService/GetTiposIvaResponse")]
        FacturaElectronica.Afip.Ws.Wsfe.IvaTipoResponse GetTiposIva(FacturaElectronica.Afip.Ws.Wsfe.FEAuthRequest feAuthRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAfipWrapperService/GetTiposOpcional", ReplyAction="http://tempuri.org/IAfipWrapperService/GetTiposOpcionalResponse")]
        FacturaElectronica.Afip.Ws.Wsfe.OpcionalTipoResponse GetTiposOpcional(FacturaElectronica.Afip.Ws.Wsfe.FEAuthRequest feAuthRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAfipWrapperService/CompTotXRequest", ReplyAction="http://tempuri.org/IAfipWrapperService/CompTotXRequestResponse")]
        FacturaElectronica.Afip.Ws.Wsfe.FERegXReqResponse CompTotXRequest(FacturaElectronica.Afip.Ws.Wsfe.FEAuthRequest feAuthRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAfipWrapperService/GetTiposDoc", ReplyAction="http://tempuri.org/IAfipWrapperService/GetTiposDocResponse")]
        FacturaElectronica.Afip.Ws.Wsfe.DocTipoResponse GetTiposDoc(FacturaElectronica.Afip.Ws.Wsfe.FEAuthRequest feAuthRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAfipWrapperService/CompUltimoAutorizado", ReplyAction="http://tempuri.org/IAfipWrapperService/CompUltimoAutorizadoResponse")]
        FacturaElectronica.Afip.Ws.Wsfe.FERecuperaLastCbteResponse CompUltimoAutorizado(FacturaElectronica.Afip.Ws.Wsfe.FEAuthRequest feAuthRequest, int ptoVta, int cbteTipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAfipWrapperService/CompConsultar", ReplyAction="http://tempuri.org/IAfipWrapperService/CompConsultarResponse")]
        FacturaElectronica.Afip.Ws.Wsfe.FECompConsultaResponse CompConsultar(FacturaElectronica.Afip.Ws.Wsfe.FEAuthRequest feAuthRequest, FacturaElectronica.Afip.Ws.Wsfe.FECompConsultaReq feCompConsultaReq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAfipWrapperService/GetTiposConcepto", ReplyAction="http://tempuri.org/IAfipWrapperService/GetTiposConceptoResponse")]
        FacturaElectronica.Afip.Ws.Wsfe.ConceptoTipoResponse GetTiposConcepto(FacturaElectronica.Afip.Ws.Wsfe.FEAuthRequest feAuthRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAfipWrapperService/ObtenerTicket", ReplyAction="http://tempuri.org/IAfipWrapperService/ObtenerTicketResponse")]
        FacturaElectronica.Afip.Ws.Wsfe.FEAuthRequest ObtenerTicket();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAfipWrapperService/AutorizarComprobanteExportacion", ReplyAction="http://tempuri.org/IAfipWrapperService/AutorizarComprobanteExportacionResponse")]
        FacturaElectronica.Afip.Ws.Wsfex.FEXResponseAuthorize AutorizarComprobanteExportacion(FacturaElectronica.Afip.Ws.Wsfex.ClsFEXAuthRequest fexAuthRequest, FacturaElectronica.Afip.Ws.Wsfex.ClsFEXRequest fexRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAfipWrapperService/CheckPermiso", ReplyAction="http://tempuri.org/IAfipWrapperService/CheckPermisoResponse")]
        FacturaElectronica.Afip.Ws.Wsfex.FEXResponse_CheckPermiso CheckPermiso(FacturaElectronica.Afip.Ws.Wsfex.ClsFEXAuthRequest fexAuthRequest, string idPermiso, int destMerc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAfipWrapperService/GetComprobante", ReplyAction="http://tempuri.org/IAfipWrapperService/GetComprobanteResponse")]
        FacturaElectronica.Afip.Ws.Wsfex.FEXGetCMPResponse GetComprobante(FacturaElectronica.Afip.Ws.Wsfex.ClsFEXAuthRequest fexAuthRequest, FacturaElectronica.Afip.Ws.Wsfex.ClsFEXGetCMP fexGetCmp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAfipWrapperService/GetUltimoComprobanteAutorizado", ReplyAction="http://tempuri.org/IAfipWrapperService/GetUltimoComprobanteAutorizadoResponse")]
        FacturaElectronica.Afip.Ws.Wsfex.FEXResponseLast_CMP GetUltimoComprobanteAutorizado(FacturaElectronica.Afip.Ws.Wsfex.ClsFEX_LastCMP fexLastCmp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAfipWrapperService/GetLastId", ReplyAction="http://tempuri.org/IAfipWrapperService/GetLastIdResponse")]
        FacturaElectronica.Afip.Ws.Wsfex.FEXResponse_LastID GetLastId(FacturaElectronica.Afip.Ws.Wsfex.ClsFEXAuthRequest fexAuthRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAfipWrapperService/GetTiposComprobantes", ReplyAction="http://tempuri.org/IAfipWrapperService/GetTiposComprobantesResponse")]
        FacturaElectronica.Afip.Ws.Wsfex.FEXResponse_Cbte_Tipo GetTiposComprobantes(FacturaElectronica.Afip.Ws.Wsfex.ClsFEXAuthRequest auth);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAfipWrapperService/GetFexCotizacion", ReplyAction="http://tempuri.org/IAfipWrapperService/GetFexCotizacionResponse")]
        FacturaElectronica.Afip.Ws.Wsfex.FEXResponse_Ctz GetFexCotizacion(FacturaElectronica.Afip.Ws.Wsfex.ClsFEXAuthRequest fexAuthRequest, string monId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAfipWrapperService/GetCuits", ReplyAction="http://tempuri.org/IAfipWrapperService/GetCuitsResponse")]
        FacturaElectronica.Afip.Ws.Wsfex.FEXResponse_DST_cuit GetCuits(FacturaElectronica.Afip.Ws.Wsfex.ClsFEXAuthRequest fexAuthRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAfipWrapperService/GetPaises", ReplyAction="http://tempuri.org/IAfipWrapperService/GetPaisesResponse")]
        FacturaElectronica.Afip.Ws.Wsfex.FEXResponse_DST_pais GetPaises(FacturaElectronica.Afip.Ws.Wsfex.ClsFEXAuthRequest fexAuthRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAfipWrapperService/GetIdiomas", ReplyAction="http://tempuri.org/IAfipWrapperService/GetIdiomasResponse")]
        FacturaElectronica.Afip.Ws.Wsfex.FEXResponse_Idi GetIdiomas(FacturaElectronica.Afip.Ws.Wsfex.ClsFEXAuthRequest fexAuthRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAfipWrapperService/GetIncoterms", ReplyAction="http://tempuri.org/IAfipWrapperService/GetIncotermsResponse")]
        FacturaElectronica.Afip.Ws.Wsfex.FEXResponse_Inc GetIncoterms(FacturaElectronica.Afip.Ws.Wsfex.ClsFEXAuthRequest fexAuthRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAfipWrapperService/GetMonedas", ReplyAction="http://tempuri.org/IAfipWrapperService/GetMonedasResponse")]
        FacturaElectronica.Afip.Ws.Wsfex.FEXResponse_Mon GetMonedas(FacturaElectronica.Afip.Ws.Wsfex.ClsFEXAuthRequest fexAuthRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAfipWrapperService/GetPuntosDeVenta", ReplyAction="http://tempuri.org/IAfipWrapperService/GetPuntosDeVentaResponse")]
        FacturaElectronica.Afip.Ws.Wsfex.FEXResponse_PtoVenta GetPuntosDeVenta(FacturaElectronica.Afip.Ws.Wsfex.ClsFEXAuthRequest fexAuthRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAfipWrapperService/GetTiposDeExportacion", ReplyAction="http://tempuri.org/IAfipWrapperService/GetTiposDeExportacionResponse")]
        FacturaElectronica.Afip.Ws.Wsfex.FEXResponse_Tex GetTiposDeExportacion(FacturaElectronica.Afip.Ws.Wsfex.ClsFEXAuthRequest fexAuthRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAfipWrapperService/GetUnidadesDeMedida", ReplyAction="http://tempuri.org/IAfipWrapperService/GetUnidadesDeMedidaResponse")]
        FacturaElectronica.Afip.Ws.Wsfex.FEXResponse_Umed GetUnidadesDeMedida(FacturaElectronica.Afip.Ws.Wsfex.ClsFEXAuthRequest fexAuthRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAfipWrapperService/ObtenerTicketFex", ReplyAction="http://tempuri.org/IAfipWrapperService/ObtenerTicketFexResponse")]
        FacturaElectronica.Afip.Ws.Wsfex.ClsFEXAuthRequest ObtenerTicketFex();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAfipWrapperServiceChannel : FacturaElectronica.Ui.Win.Administrador.ServiceReferenceAfipWrapperService.IAfipWrapperService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AfipWrapperServiceClient : System.ServiceModel.ClientBase<FacturaElectronica.Ui.Win.Administrador.ServiceReferenceAfipWrapperService.IAfipWrapperService>, FacturaElectronica.Ui.Win.Administrador.ServiceReferenceAfipWrapperService.IAfipWrapperService {
        
        public AfipWrapperServiceClient() {
        }
        
        public AfipWrapperServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AfipWrapperServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AfipWrapperServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AfipWrapperServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FacturaElectronica.Afip.Ws.Wsfe.MonedaResponse GetTiposMonedas(FacturaElectronica.Afip.Ws.Wsfe.FEAuthRequest feAuthRequest) {
            return base.Channel.GetTiposMonedas(feAuthRequest);
        }
        
        public FacturaElectronica.Afip.Ws.Wsfe.FECotizacionResponse GetCotizacion(FacturaElectronica.Afip.Ws.Wsfe.FEAuthRequest feAuthRequest, string MonId) {
            return base.Channel.GetCotizacion(feAuthRequest, MonId);
        }
        
        public FacturaElectronica.Afip.Ws.Wsfe.CbteTipoResponse GetTiposCbte(FacturaElectronica.Afip.Ws.Wsfe.FEAuthRequest feAuthRequest) {
            return base.Channel.GetTiposCbte(feAuthRequest);
        }
        
        public FacturaElectronica.Afip.Ws.Wsfe.FETributoResponse GetTiposTributos(FacturaElectronica.Afip.Ws.Wsfe.FEAuthRequest feAuthRequest) {
            return base.Channel.GetTiposTributos(feAuthRequest);
        }
        
        public FacturaElectronica.Afip.Ws.Wsfe.IvaTipoResponse GetTiposIva(FacturaElectronica.Afip.Ws.Wsfe.FEAuthRequest feAuthRequest) {
            return base.Channel.GetTiposIva(feAuthRequest);
        }
        
        public FacturaElectronica.Afip.Ws.Wsfe.OpcionalTipoResponse GetTiposOpcional(FacturaElectronica.Afip.Ws.Wsfe.FEAuthRequest feAuthRequest) {
            return base.Channel.GetTiposOpcional(feAuthRequest);
        }
        
        public FacturaElectronica.Afip.Ws.Wsfe.FERegXReqResponse CompTotXRequest(FacturaElectronica.Afip.Ws.Wsfe.FEAuthRequest feAuthRequest) {
            return base.Channel.CompTotXRequest(feAuthRequest);
        }
        
        public FacturaElectronica.Afip.Ws.Wsfe.DocTipoResponse GetTiposDoc(FacturaElectronica.Afip.Ws.Wsfe.FEAuthRequest feAuthRequest) {
            return base.Channel.GetTiposDoc(feAuthRequest);
        }
        
        public FacturaElectronica.Afip.Ws.Wsfe.FERecuperaLastCbteResponse CompUltimoAutorizado(FacturaElectronica.Afip.Ws.Wsfe.FEAuthRequest feAuthRequest, int ptoVta, int cbteTipo) {
            return base.Channel.CompUltimoAutorizado(feAuthRequest, ptoVta, cbteTipo);
        }
        
        public FacturaElectronica.Afip.Ws.Wsfe.FECompConsultaResponse CompConsultar(FacturaElectronica.Afip.Ws.Wsfe.FEAuthRequest feAuthRequest, FacturaElectronica.Afip.Ws.Wsfe.FECompConsultaReq feCompConsultaReq) {
            return base.Channel.CompConsultar(feAuthRequest, feCompConsultaReq);
        }
        
        public FacturaElectronica.Afip.Ws.Wsfe.ConceptoTipoResponse GetTiposConcepto(FacturaElectronica.Afip.Ws.Wsfe.FEAuthRequest feAuthRequest) {
            return base.Channel.GetTiposConcepto(feAuthRequest);
        }
        
        public FacturaElectronica.Afip.Ws.Wsfe.FEAuthRequest ObtenerTicket() {
            return base.Channel.ObtenerTicket();
        }
        
        public FacturaElectronica.Afip.Ws.Wsfex.FEXResponseAuthorize AutorizarComprobanteExportacion(FacturaElectronica.Afip.Ws.Wsfex.ClsFEXAuthRequest fexAuthRequest, FacturaElectronica.Afip.Ws.Wsfex.ClsFEXRequest fexRequest) {
            return base.Channel.AutorizarComprobanteExportacion(fexAuthRequest, fexRequest);
        }
        
        public FacturaElectronica.Afip.Ws.Wsfex.FEXResponse_CheckPermiso CheckPermiso(FacturaElectronica.Afip.Ws.Wsfex.ClsFEXAuthRequest fexAuthRequest, string idPermiso, int destMerc) {
            return base.Channel.CheckPermiso(fexAuthRequest, idPermiso, destMerc);
        }
        
        public FacturaElectronica.Afip.Ws.Wsfex.FEXGetCMPResponse GetComprobante(FacturaElectronica.Afip.Ws.Wsfex.ClsFEXAuthRequest fexAuthRequest, FacturaElectronica.Afip.Ws.Wsfex.ClsFEXGetCMP fexGetCmp) {
            return base.Channel.GetComprobante(fexAuthRequest, fexGetCmp);
        }
        
        public FacturaElectronica.Afip.Ws.Wsfex.FEXResponseLast_CMP GetUltimoComprobanteAutorizado(FacturaElectronica.Afip.Ws.Wsfex.ClsFEX_LastCMP fexLastCmp) {
            return base.Channel.GetUltimoComprobanteAutorizado(fexLastCmp);
        }
        
        public FacturaElectronica.Afip.Ws.Wsfex.FEXResponse_LastID GetLastId(FacturaElectronica.Afip.Ws.Wsfex.ClsFEXAuthRequest fexAuthRequest) {
            return base.Channel.GetLastId(fexAuthRequest);
        }
        
        public FacturaElectronica.Afip.Ws.Wsfex.FEXResponse_Cbte_Tipo GetTiposComprobantes(FacturaElectronica.Afip.Ws.Wsfex.ClsFEXAuthRequest auth) {
            return base.Channel.GetTiposComprobantes(auth);
        }
        
        public FacturaElectronica.Afip.Ws.Wsfex.FEXResponse_Ctz GetFexCotizacion(FacturaElectronica.Afip.Ws.Wsfex.ClsFEXAuthRequest fexAuthRequest, string monId) {
            return base.Channel.GetFexCotizacion(fexAuthRequest, monId);
        }
        
        public FacturaElectronica.Afip.Ws.Wsfex.FEXResponse_DST_cuit GetCuits(FacturaElectronica.Afip.Ws.Wsfex.ClsFEXAuthRequest fexAuthRequest) {
            return base.Channel.GetCuits(fexAuthRequest);
        }
        
        public FacturaElectronica.Afip.Ws.Wsfex.FEXResponse_DST_pais GetPaises(FacturaElectronica.Afip.Ws.Wsfex.ClsFEXAuthRequest fexAuthRequest) {
            return base.Channel.GetPaises(fexAuthRequest);
        }
        
        public FacturaElectronica.Afip.Ws.Wsfex.FEXResponse_Idi GetIdiomas(FacturaElectronica.Afip.Ws.Wsfex.ClsFEXAuthRequest fexAuthRequest) {
            return base.Channel.GetIdiomas(fexAuthRequest);
        }
        
        public FacturaElectronica.Afip.Ws.Wsfex.FEXResponse_Inc GetIncoterms(FacturaElectronica.Afip.Ws.Wsfex.ClsFEXAuthRequest fexAuthRequest) {
            return base.Channel.GetIncoterms(fexAuthRequest);
        }
        
        public FacturaElectronica.Afip.Ws.Wsfex.FEXResponse_Mon GetMonedas(FacturaElectronica.Afip.Ws.Wsfex.ClsFEXAuthRequest fexAuthRequest) {
            return base.Channel.GetMonedas(fexAuthRequest);
        }
        
        public FacturaElectronica.Afip.Ws.Wsfex.FEXResponse_PtoVenta GetPuntosDeVenta(FacturaElectronica.Afip.Ws.Wsfex.ClsFEXAuthRequest fexAuthRequest) {
            return base.Channel.GetPuntosDeVenta(fexAuthRequest);
        }
        
        public FacturaElectronica.Afip.Ws.Wsfex.FEXResponse_Tex GetTiposDeExportacion(FacturaElectronica.Afip.Ws.Wsfex.ClsFEXAuthRequest fexAuthRequest) {
            return base.Channel.GetTiposDeExportacion(fexAuthRequest);
        }
        
        public FacturaElectronica.Afip.Ws.Wsfex.FEXResponse_Umed GetUnidadesDeMedida(FacturaElectronica.Afip.Ws.Wsfex.ClsFEXAuthRequest fexAuthRequest) {
            return base.Channel.GetUnidadesDeMedida(fexAuthRequest);
        }
        
        public FacturaElectronica.Afip.Ws.Wsfex.ClsFEXAuthRequest ObtenerTicketFex() {
            return base.Channel.ObtenerTicketFex();
        }
    }
}
