//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacturaElectronica.Ui.Win.Administrador.ServiceReferenceComprobanteService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceComprobanteService.IComprobanteService")]
    public interface IComprobanteService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComprobanteService/ObtenerTiposComprobantes", ReplyAction="http://tempuri.org/IComprobanteService/ObtenerTiposComprobantesResponse")]
        System.Collections.Generic.List<FacturaElectronica.Common.Contracts.TipoComprobanteDto> ObtenerTiposComprobantes();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IComprobanteServiceChannel : FacturaElectronica.Ui.Win.Administrador.ServiceReferenceComprobanteService.IComprobanteService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ComprobanteServiceClient : System.ServiceModel.ClientBase<FacturaElectronica.Ui.Win.Administrador.ServiceReferenceComprobanteService.IComprobanteService>, FacturaElectronica.Ui.Win.Administrador.ServiceReferenceComprobanteService.IComprobanteService {
        
        public ComprobanteServiceClient() {
        }
        
        public ComprobanteServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ComprobanteServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ComprobanteServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ComprobanteServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<FacturaElectronica.Common.Contracts.TipoComprobanteDto> ObtenerTiposComprobantes() {
            return base.Channel.ObtenerTiposComprobantes();
        }
    }
}
