//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacturaElectronica.Ui.Win.Administrador.ServiceReferenceMaestro {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceMaestro.IMaestrosService")]
    public interface IMaestrosService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaestrosService/ObtenerWebServicesAfip", ReplyAction="http://tempuri.org/IMaestrosService/ObtenerWebServicesAfipResponse")]
        System.Collections.Generic.List<FacturaElectronica.Common.Contracts.WebServiceAfipDto> ObtenerWebServicesAfip();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMaestrosServiceChannel : FacturaElectronica.Ui.Win.Administrador.ServiceReferenceMaestro.IMaestrosService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MaestrosServiceClient : System.ServiceModel.ClientBase<FacturaElectronica.Ui.Win.Administrador.ServiceReferenceMaestro.IMaestrosService>, FacturaElectronica.Ui.Win.Administrador.ServiceReferenceMaestro.IMaestrosService {
        
        public MaestrosServiceClient() {
        }
        
        public MaestrosServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MaestrosServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MaestrosServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MaestrosServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<FacturaElectronica.Common.Contracts.WebServiceAfipDto> ObtenerWebServicesAfip() {
            return base.Channel.ObtenerWebServicesAfip();
        }
    }
}
