//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacturaElectronica.Ui.Win.Administrador.ServiceReferenceAfipWrapper {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceAfipWrapper.IAfipWrapperService")]
    public interface IAfipWrapperService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAfipWrapperService/GetTiposMonedas", ReplyAction="http://tempuri.org/IAfipWrapperService/GetTiposMonedasResponse")]
        FacturaElectronica.Afip.Ws.Wsfe.MonedaResponse GetTiposMonedas(FacturaElectronica.Afip.Ws.Wsfe.FEAuthRequest feAuthRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAfipWrapperService/GetCotizacion", ReplyAction="http://tempuri.org/IAfipWrapperService/GetCotizacionResponse")]
        FacturaElectronica.Afip.Ws.Wsfe.FECotizacionResponse GetCotizacion(FacturaElectronica.Afip.Ws.Wsfe.FEAuthRequest feAuthRequest, string MonId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAfipWrapperService/GetTiposCbte", ReplyAction="http://tempuri.org/IAfipWrapperService/GetTiposCbteResponse")]
        FacturaElectronica.Afip.Ws.Wsfe.CbteTipoResponse GetTiposCbte(FacturaElectronica.Afip.Ws.Wsfe.FEAuthRequest feAuthRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAfipWrapperService/GetTiposTributos", ReplyAction="http://tempuri.org/IAfipWrapperService/GetTiposTributosResponse")]
        FacturaElectronica.Afip.Ws.Wsfe.FETributoResponse GetTiposTributos(FacturaElectronica.Afip.Ws.Wsfe.FEAuthRequest feAuthRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAfipWrapperService/GetTiposIva", ReplyAction="http://tempuri.org/IAfipWrapperService/GetTiposIvaResponse")]
        FacturaElectronica.Afip.Ws.Wsfe.IvaTipoResponse GetTiposIva(FacturaElectronica.Afip.Ws.Wsfe.FEAuthRequest feAuthRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAfipWrapperService/GetTiposOpcional", ReplyAction="http://tempuri.org/IAfipWrapperService/GetTiposOpcionalResponse")]
        FacturaElectronica.Afip.Ws.Wsfe.OpcionalTipoResponse GetTiposOpcional(FacturaElectronica.Afip.Ws.Wsfe.FEAuthRequest feAuthRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAfipWrapperService/CompTotXRequest", ReplyAction="http://tempuri.org/IAfipWrapperService/CompTotXRequestResponse")]
        FacturaElectronica.Afip.Ws.Wsfe.FERegXReqResponse CompTotXRequest(FacturaElectronica.Afip.Ws.Wsfe.FEAuthRequest feAuthRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAfipWrapperService/GetTiposDoc", ReplyAction="http://tempuri.org/IAfipWrapperService/GetTiposDocResponse")]
        FacturaElectronica.Afip.Ws.Wsfe.DocTipoResponse GetTiposDoc(FacturaElectronica.Afip.Ws.Wsfe.FEAuthRequest feAuthRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAfipWrapperService/CompUltimoAutorizado", ReplyAction="http://tempuri.org/IAfipWrapperService/CompUltimoAutorizadoResponse")]
        FacturaElectronica.Afip.Ws.Wsfe.FERecuperaLastCbteResponse CompUltimoAutorizado(FacturaElectronica.Afip.Ws.Wsfe.FEAuthRequest feAuthRequest, int ptoVta, int cbteTipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAfipWrapperService/CompConsultar", ReplyAction="http://tempuri.org/IAfipWrapperService/CompConsultarResponse")]
        FacturaElectronica.Afip.Ws.Wsfe.FECompConsultaResponse CompConsultar(FacturaElectronica.Afip.Ws.Wsfe.FEAuthRequest feAuthRequest, FacturaElectronica.Afip.Ws.Wsfe.FECompConsultaReq feCompConsultaReq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAfipWrapperService/GetTiposConcepto", ReplyAction="http://tempuri.org/IAfipWrapperService/GetTiposConceptoResponse")]
        FacturaElectronica.Afip.Ws.Wsfe.ConceptoTipoResponse GetTiposConcepto(FacturaElectronica.Afip.Ws.Wsfe.FEAuthRequest feAuthRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAfipWrapperService/ObtenerTicket", ReplyAction="http://tempuri.org/IAfipWrapperService/ObtenerTicketResponse")]
        FacturaElectronica.Afip.Ws.Wsfe.FEAuthRequest ObtenerTicket();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAfipWrapperServiceChannel : FacturaElectronica.Ui.Win.Administrador.ServiceReferenceAfipWrapper.IAfipWrapperService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AfipWrapperServiceClient : System.ServiceModel.ClientBase<FacturaElectronica.Ui.Win.Administrador.ServiceReferenceAfipWrapper.IAfipWrapperService>, FacturaElectronica.Ui.Win.Administrador.ServiceReferenceAfipWrapper.IAfipWrapperService {
        
        public AfipWrapperServiceClient() {
        }
        
        public AfipWrapperServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AfipWrapperServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AfipWrapperServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AfipWrapperServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FacturaElectronica.Afip.Ws.Wsfe.MonedaResponse GetTiposMonedas(FacturaElectronica.Afip.Ws.Wsfe.FEAuthRequest feAuthRequest) {
            return base.Channel.GetTiposMonedas(feAuthRequest);
        }
        
        public FacturaElectronica.Afip.Ws.Wsfe.FECotizacionResponse GetCotizacion(FacturaElectronica.Afip.Ws.Wsfe.FEAuthRequest feAuthRequest, string MonId) {
            return base.Channel.GetCotizacion(feAuthRequest, MonId);
        }
        
        public FacturaElectronica.Afip.Ws.Wsfe.CbteTipoResponse GetTiposCbte(FacturaElectronica.Afip.Ws.Wsfe.FEAuthRequest feAuthRequest) {
            return base.Channel.GetTiposCbte(feAuthRequest);
        }
        
        public FacturaElectronica.Afip.Ws.Wsfe.FETributoResponse GetTiposTributos(FacturaElectronica.Afip.Ws.Wsfe.FEAuthRequest feAuthRequest) {
            return base.Channel.GetTiposTributos(feAuthRequest);
        }
        
        public FacturaElectronica.Afip.Ws.Wsfe.IvaTipoResponse GetTiposIva(FacturaElectronica.Afip.Ws.Wsfe.FEAuthRequest feAuthRequest) {
            return base.Channel.GetTiposIva(feAuthRequest);
        }
        
        public FacturaElectronica.Afip.Ws.Wsfe.OpcionalTipoResponse GetTiposOpcional(FacturaElectronica.Afip.Ws.Wsfe.FEAuthRequest feAuthRequest) {
            return base.Channel.GetTiposOpcional(feAuthRequest);
        }
        
        public FacturaElectronica.Afip.Ws.Wsfe.FERegXReqResponse CompTotXRequest(FacturaElectronica.Afip.Ws.Wsfe.FEAuthRequest feAuthRequest) {
            return base.Channel.CompTotXRequest(feAuthRequest);
        }
        
        public FacturaElectronica.Afip.Ws.Wsfe.DocTipoResponse GetTiposDoc(FacturaElectronica.Afip.Ws.Wsfe.FEAuthRequest feAuthRequest) {
            return base.Channel.GetTiposDoc(feAuthRequest);
        }
        
        public FacturaElectronica.Afip.Ws.Wsfe.FERecuperaLastCbteResponse CompUltimoAutorizado(FacturaElectronica.Afip.Ws.Wsfe.FEAuthRequest feAuthRequest, int ptoVta, int cbteTipo) {
            return base.Channel.CompUltimoAutorizado(feAuthRequest, ptoVta, cbteTipo);
        }
        
        public FacturaElectronica.Afip.Ws.Wsfe.FECompConsultaResponse CompConsultar(FacturaElectronica.Afip.Ws.Wsfe.FEAuthRequest feAuthRequest, FacturaElectronica.Afip.Ws.Wsfe.FECompConsultaReq feCompConsultaReq) {
            return base.Channel.CompConsultar(feAuthRequest, feCompConsultaReq);
        }
        
        public FacturaElectronica.Afip.Ws.Wsfe.ConceptoTipoResponse GetTiposConcepto(FacturaElectronica.Afip.Ws.Wsfe.FEAuthRequest feAuthRequest) {
            return base.Channel.GetTiposConcepto(feAuthRequest);
        }
        
        public FacturaElectronica.Afip.Ws.Wsfe.FEAuthRequest ObtenerTicket() {
            return base.Channel.ObtenerTicket();
        }
    }
}
