//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacturaElectronica.Ui.Win.Administrador.ServiceReferenceSubidaArchivo {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceSubidaArchivo.ISubidaArchivoService")]
    public interface ISubidaArchivoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubidaArchivoService/CrearNuevaCorrida", ReplyAction="http://tempuri.org/ISubidaArchivoService/CrearNuevaCorridaResponse")]
        FacturaElectronica.Common.Contracts.CorridaSubidaArchivoDto CrearNuevaCorrida();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISubidaArchivoService/EjecutarCorrida")]
        void EjecutarCorrida(long corridaId, System.Collections.Generic.List<string> files);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubidaArchivoService/ObtenerCorridas", ReplyAction="http://tempuri.org/ISubidaArchivoService/ObtenerCorridasResponse")]
        System.Collections.Generic.List<FacturaElectronica.Common.Contracts.CorridaSubidaArchivoDto> ObtenerCorridas(FacturaElectronica.Common.Contracts.Search.CorridaSubidaArchivoSearch search);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISubidaArchivoServiceChannel : FacturaElectronica.Ui.Win.Administrador.ServiceReferenceSubidaArchivo.ISubidaArchivoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SubidaArchivoServiceClient : System.ServiceModel.ClientBase<FacturaElectronica.Ui.Win.Administrador.ServiceReferenceSubidaArchivo.ISubidaArchivoService>, FacturaElectronica.Ui.Win.Administrador.ServiceReferenceSubidaArchivo.ISubidaArchivoService {
        
        public SubidaArchivoServiceClient() {
        }
        
        public SubidaArchivoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SubidaArchivoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SubidaArchivoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SubidaArchivoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FacturaElectronica.Common.Contracts.CorridaSubidaArchivoDto CrearNuevaCorrida() {
            return base.Channel.CrearNuevaCorrida();
        }
        
        public void EjecutarCorrida(long corridaId, System.Collections.Generic.List<string> files) {
            base.Channel.EjecutarCorrida(corridaId, files);
        }
        
        public System.Collections.Generic.List<FacturaElectronica.Common.Contracts.CorridaSubidaArchivoDto> ObtenerCorridas(FacturaElectronica.Common.Contracts.Search.CorridaSubidaArchivoSearch search) {
            return base.Channel.ObtenerCorridas(search);
        }
    }
}
